# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6477f4e73701c09d1787e99dd66038f00a220857415c4524ae1bc65aa6433fe0bab5a2b9dbd3a9b1455e3f68a6dbe9171e2bcb2d711e3cf49ebe788583cc7417

test:
  secret_key_base: 9d14eb4c09a68efd54c3df469fd5bd1687e8e3cb7f3fc14c9da4342612dd490d40a8f7fd25b91890f45e15ec2270a9eec7815a991356b357f9aba656ca460dd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
